#!/usr/bin/env python3
"""Sinh Assets/Game/Scripts/UIScripts/FloorStoryGame/Flow/FsModData.cs từ khai báo mô-đun `MOD` trong fs/fs_flow.js
(tham số + giá trị MẶC ĐỊNH của gen/view/judge/reveal) để Unity dùng đúng cùng mặc định với web builder.
Chạy lại mỗi khi sửa `MOD` (thêm/sửa tham số):  python Tools/floorstory_pack/gen_mod_cs.py   Cần node."""
import json, os, subprocess
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
FS = os.path.join(REPO, 'WebTools', 'GenericGameBuilder', 'fs')
OUT = os.path.join(REPO, 'Assets', 'Game', 'Scripts', 'UIScripts', 'FloorStoryGame', 'Flow', 'FsModData.cs')
js = ("global.window=global; global.document={createElement:()=>({getContext:()=>null,style:{}}),head:{appendChild(){}}};"
      "const fs=require('fs');for(const f of ['fs_core.js','fs_expr.js','fs_game.js','fs_act.js','fs_flow.js']){(0,eval)(fs.readFileSync(process.argv[1]+'/'+f,'utf8'));}"
      "const M=window.FSW.MOD, o={};for(const k of ['gen','view','judge']){o[k]={};for(const t in M[k]){o[k][t]={};for(const p in M[k][t].p){const d=M[k][t].p[p];o[k][t][p]={t:d.type,d:d.def};}}}"
      "o.reveal={};for(const p in M.reveal.p){const d=M.reveal.p[p];o.reveal[p]={t:d.type,d:d.def};}"
      "process.stdout.write(JSON.stringify(o));")
raw = subprocess.check_output(['node', '-e', js, FS]).decode('utf-8')
data = json.loads(raw)
cs = ('// <auto-generated> bởi Tools/floorstory_pack/gen_mod_cs.py từ MOD trong fs_flow.js — ĐỪNG sửa tay. </auto-generated>\n'
      '/// <summary>Tham số + mặc định của mô-đun flow (khớp web builder). Dạng: {gen|view|judge|reveal}.{type}.{param} = {t: kiểu, d: mặc định}.</summary>\n'
      'public static class FsModData\n{\n    public const string Json = @"' + json.dumps(data, ensure_ascii=False, separators=(',', ':')).replace('"', '""') + '";\n}\n')
open(OUT, 'w', encoding='utf-8', newline='\n').write(cs)
print('FsModData.cs', len(raw), 'bytes')
